name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: vndangkhoa
          outputs: |
            dist/snake-dark.svg?palette=github-dark
            dist/snake-light.svg?palette=github-light

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
